name: Build Image on Commit and Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'docker-bake.hcl'
      # - './devcontainer/**'      
    tags:
      - 'v*'

  workflow_dispatch:


env:
  DOCKERHUB_SLUG: ngeorger/discourse-k3s-selfhosted
  GHCR_SLUG: ghcr.io/sredevopsdev/discourse-k3s-selfhosted


jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -  
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        # Only run if the commit is a tag (i.e. a release).
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: false
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tags: |
            type=raw,value=latest
            type=sha
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=stable,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: image-all
          push: true
